server:
  port: 8080
spring:
  application:
    name: gateway-server
  jmx:
    defaultDomain: gateway-server

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    # Default values comes from org.springframework.cloud.netflix.eurek.EurekaClientConfigBean
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# A prefix that can added to beginning of all requests. 
#zuul.prefix=/api

# Disable accessing services using service name (i.e. gallery-service).
# They should be only accessed through the path defined below.
# Link: https://stackoverflow.com/questions/46317388/zuul-service-name-exposed-instead-of-route-path-only
zuul:
  ignoredServices: '*'
  routes:
    autotorinoService:
      path: /autotorino/**
      serviceId: autotorino-service
    auth-service:
      path: /auth/**
      serviceId: AUTH-SERVICE
      stripPrefix: false
      sensitiveHeader: Cookie,Set-Cookie 
