server:
  port: 8080
spring:
  application:
    name: gateway-server
  jmx:
    defaultDomain: gateway-server

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    # Default values comes from org.springframework.cloud.netflix.eurek.EurekaClientConfigBean
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  ignoredServices: '*'
  routes:
    testService:
      path: /test/**
      serviceId: test-service

